spring:
    main:
        banner-mode: 'off'

logging:
    level:
        org:
            hibernate:
                SQL: debug
                stat: debug
                type: trace
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
